### ISSUE TITLE
Server crash when attempting to target user who has disconnected

### ISSUE THREAD

**Issue by paralinguist** [paralinguist/Chestral#18]
Check for valid ID before attempting to apply effect.

**Comment by RedBlueCarrots** [comment]
when does this actually occur in the code? On a brief glanceI can't see where a disconnected id could be referenced

**Comment by paralinguist** [comment]
I suspect it's introduced with the telegraphed attack - it picks a target and then hits it 8 or so seconds later.
If the target disconnects in the meantime, it'll try to target something that isn't there.
A simple if should sort it.

**Comment by RedBlueCarrots** [comment]
Untested solution added - I think the issue is with scene referencing not strictly with IDs, and I'm not 100% sure my solution sufficiently checks for this
